Vladimir: main.o grafo.o vladimir.o
				  gcc main.o grafo.o vladimir.o -o Vladimir

main.o: main.c
	gcc -c main.c

vladimir.o : vladimir.c vladimir.h
	gcc -c vladimir.c

grafo.o : grafo.c grafo.h
	gcc -c grafo.c



